admins: [Arcade_hi]

forwards:
  - source: asdacvzcxv
    dest: [https://t.me/bsdfvsadv]
show_forwarded_from: false
plugins:
  replace:
    text:
      "@TsePress": 🆔@Rahnamayebourse_pluse
      "@enigma_investing": 🆔@Rahnamayebourse_pluse
      "@ebarez": 🆔@Rahnamayebourse_pluse
      "@tsepress": 🆔@Rahnamayebourse_pluse
      "http://TsePress.com": خبر#
      "TsePress.com": خبر#
      "@TSEPRESS": 🆔@Rahnamayebourse_pluse
  filter:

    text:
      blacklist: ["yun.ir"]
