admins:
- Arcade_hi
forwards:
- source: asdacvzcxv
  dest:
  - https://t.me/bsdfvsadv
  offset: 48
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 0.0
plugins:
  replace:
    text:
      '@TsePress': 🆔@Rahnamayebourse_pluse
      '@enigma_investing': 🆔@Rahnamayebourse_pluse
      '@ebarez': 🆔@Rahnamayebourse_pluse
      '@tsepress': 🆔@Rahnamayebourse_pluse
      http://TsePress.com: خبر#
      TsePress.com: خبر#
      '@TSEPRESS': 🆔@Rahnamayebourse_pluse
  filter:
    text:
      blacklist:
      - yun.ir
